title:              DEVHWAN
email:              chlim428@gmail.com
description:        A Blog to Record What I Learned
author:             chaehwanlim
baseurl:            ""
url:                "https://chaehwanlim.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    BlackrockDigital
facebook_username:  StartBootstrap
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

google_fonts: "Inter:300,400,500,700, Noto+Sans+KR:300,400,500,700"